# These are supported funding model platforms

#github: tunnckoCore # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: tunnckoCore # Replace with a single Patreon username
#open_collective: # Replace with a single Open Collective username
custom: https://tunnckocore.com/opensource # Replace with a single custom sponsorship URL
