# These settings are synced to GitHub by https://probot.github.io/apps/settings/

repository:
  # See https://developer.github.com/v3/repos/#edit for all available settings.

  # The name of the repository. Changing this will rename the repository
  # name: repo-name

  # A short description of the repository that will show up on GitHub
  # description: description of repo

  # A URL with more information about the repository
  homepage: https://tunnckocore.com/opensource

  # A comma-separated list of topics to set on the repository
  topics: tunnckocore, tunnckocorehq, opensource, software, javascript

  # Either `true` to make the repository private, or `false` to make it public.
  private: false

  # Either `true` to enable issues for this repository, `false` to disable them.
  has_issues: true

  # Either `true` to enable projects for this repository, or `false` to disable them.
  # If projects are disabled for the organization, passing `true` will cause an API error.
  has_projects: false

  # Either `true` to enable the wiki for this repository, `false` to disable it.
  has_wiki: false

  # Either `true` to enable downloads for this repository, `false` to disable them.
  has_downloads: true

  # Updates the default branch for this repository.
  default_branch: master

  # Either `true` to allow squash-merging pull requests, or `false` to prevent
  # squash-merging.
  allow_squash_merge: true

  # Either `true` to allow merging pull requests with a merge commit, or `false`
  # to prevent merging pull requests with merge commits.
  allow_merge_commit: false

  # Either `true` to allow rebase-merging pull requests, or `false` to prevent
  # rebase-merging.
  allow_rebase_merge: true

# Labels: define labels for Issues and Pull Requests



labels:
  - name: duplicate
    color: "a3a3a3"
    description: This issue or pull request topic/problem already exists

  - name: good first issue
    color: "1d76db"
    description: Good for newcomers and first-time contributors.

  - name: Priority: Critical
    color: "ee0701"
    description: This should be dealt with ASAP. Not fixing this issue would be a serious error.

  - name: Priority: High
    color: "d93f0b"
    description: After critical issues are fixed, these should be dealt with before any further issues.

  - name: Priority: Medium
    color: "fbca04"
    description: This issue may be useful, and needs some attention.

  - name: Priority: Low
    color: "0e8a16"
    description: This issue can probably be picked up by anyone looking to contribute to the project, as an entry fix.

  - name: Status: Available
    color: "c2e0c6"
    description: No one has claimed responsibility for resolving this issue. Generally this will be applied to bugs and enhancement issues, but may be applied to others.

  - name: Status: Accepted
    color: "78cc35"
    description: It's clear what the subject of the issue is about, and what the resolution should be.

  - name: Status: Blocked
    color: "d73a4a"
    description: There is another issue that needs to be resolved first, or a specific person is required to comment or reply to progress. There may also be some external blocker.

  - name: Status: Abandoned
    color: "000000"
    description: It's believed that this issue is no longer important to the requestor and no one else has shown an interest in it.

  - name: Status: In Progress
    color: "cccccc"
    description: This issue is being worked on, and has someone assigned.

  - name: Status: On Hold
    color: "e99695"
    description: Similar to blocked, but is assigned to someone. May also be assigned to someone because of their experience, but it's recognised they are unable to process the issue at this time.

  - name: Status: Completed
    color: "adff60"
    description: Issue with steps to reproduce the bug that’s been verified by at least one reviewer.

  - name: Status: Review Needed
    color: "fbca04"
    description: The issue has a PR attached to it which needs to be reviewed. Should receive review by others in the community, and at least one member / comitter. Specifics on when merging PRs is allowed is still up for debate.

  - name: Status: Revision Needed
    color: "006b75"
    description: At least two people have seen issues in the PR that makes them uneasy. Submitter of PR needs to revise the PR related to the issue.

  - name: Type: Bug
    color: "ee0701"
    description: Inconsistencies or issues which will cause an issue or problem for users or implementors.

  - name: Type: Maintenance
    color: "fbca04"
    description: Updating phrasing or wording to make things clearer or removing ambiguity, without changing the functionality.

  - name: Type: Enhancement
    color: "d4c5f9"
    description: Most issues will probably ask for additions or changes. It's expected that this type of issue will result in a Pull Request.

  - name: Type: Question
    color: "cc317c"
    description: A query or seeking clarification on parts of the spec. Probably doesn't need the attention of everyone, just a few to help bring clarification or explain intent.

  - name: Type: Documentation
    color: "5319e7"
    description: An Issue or Pull Request for improving or updating documentation.

  - name: Status: Proposal
    color: "d4c5f9"

# Milestones: define milestones for Issues and Pull Requests
# milestones:
#   - title: milestone-title
#     description: milestone-description
#     # The state of the milestone. Either `open` or `closed`
#     state: open

# Collaborators: give specific users access to this repository.
# collaborators:
#   - username: bkeepers
#     # Note: Only valid on organization-owned repositories.
#     # The permission to grant the collaborator. Can be one of:
#     # * `pull` - can pull, but not push to or administer this repository.
#     # * `push` - can pull and push, but not administer this repository.
#     # * `admin` - can pull, push and administer this repository.
#     permission: push

#   - username: hubot
#     permission: pull

# NOTE: The APIs needed for teams are not supported yet by GitHub Apps
# https://developer.github.com/v3/apps/available-endpoints/
# teams:
#   - name: core
#     permission: admin
#   - name: docs
#     permission: push

# branches:
#   - name: master
#     # https://developer.github.com/v3/repos/branches/#update-branch-protection
#     # Branch Protection settings. Set to null to disable
#     protection:
#       # Required. Require at least one approving review on a pull request, before merging. Set to null to disable.
#       required_pull_request_reviews:
#         # The number of approvals required. (1-6)
#         required_approving_review_count: 1
#         # Dismiss approved reviews automatically when a new commit is pushed.
#         dismiss_stale_reviews: true
#         # Blocks merge until code owners have reviewed.
#         require_code_owner_reviews: true
#         # Specify which users and teams can dismiss pull request reviews. Pass an empty dismissal_restrictions object to disable. User and team dismissal_restrictions are only available for organization-owned repositories. Omit this parameter for personal repositories.
#         # dismissal_restrictions:
#         #   users: []
#         #   teams: []
#       # Required. Require status checks to pass before merging. Set to null to disable
#       required_status_checks:
#         # Required. Require branches to be up to date before merging.
#         strict: true
#         # Required. The list of status checks to require in order to merge into this branch
#         contexts: [
#           'now',
#           'now/package.json'
#         ]
#       # Required. Enforce all configured restrictions for administrators. Set to true to enforce required status checks for repository administrators. Set to null to disable.
#       enforce_admins: null
#       # Required. Restrict who can push to this branch. Team and user restrictions are only available for organization-owned repositories. Set to null to disable.
#       # restrictions:
#       #   users: []
#       #   teams: []
#       restrictions: null
