test_task:
  container:
    matrix:
      - image: node:10
      - image: node:lts

  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat yarn.lock
    populate_script: yarn install

  test_script: |
    yarn start build
