test_task:
  container:
    matrix:
      - image: node:8
      - image: node:lts
      - image: node:12

  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat yarn.lock
    populate_script: yarn install

  test_script: |
    node --version
    yarn --version
    yarn start build
