sudo: false
language: node_js

node_js:
  - '10'
  - 'node'

os:
  - linux
  - osx
  - windows

cache: yarn

notifications:
  email: false

script:
  - yarn start test

after_success: if [[ "$TRAVIS_OS_NAME" == 'linux' ]]; then yarn cov; fi
